eslint-plugin-unused-importsの導入
ycu-engine/DSC-Blog-Frontend pull request #18
Opened 2023-07-29 13:56 UTC by takuya-okada-01

## Issueへのリンク

close #12 

## やったこと

- ESLintの設定を変更し、不要なimportを自動的に削除するように設定。

## 動作確認

<img width="518" alt="image" src="https://github.com/ycu-engine/DSC-Blog-Frontend/assets/106806920/b7e3e4a8-a9da-40e0-94c2-9d09b4021b72">
<img width="528" alt="image" src="https://github.com/ycu-engine/DSC-Blog-Frontend/assets/106806920/3488c19d-31cc-48b3-87f1-4d7d1bb5b004">

## その他

- `.eslintrc.js`に[公式](https://github.com/sweepline/eslint-plugin-unused-imports)の推奨通りルールを記述したが、必要かもしくは他に必要なものはあるか。
```
rules: {
  // 省略
  'unused-imports/no-unused-imports': 'error',
  'unused-imports/no-unused-vars': [
     'warn',
     { vars: 'all', varsIgnorePattern: '^_', args: 'after-used', argsIgnorePattern: '^_' },
    ],
}
```

2023-07-29 14:08 UTC, nyatinte commented
LGTM

2023-07-29 14:10 UTC, nyatinte commented on .eslintrc.js
> +  plugins: ['jsdoc', 'unused-imports'],
LGTM👀

[🎨AirbnbのESLintルールを適応](https://github.com/ycu-engine/DSC-Blog-Frontend/pull/10/commits/759d0d23e4830cd238e90cfd8b20365b24ce0a01)

[🎨JSDocの記述を必須とするESLintの設定を追記](https://github.com/ycu-engine/DSC-Blog-Frontend/pull/10/commits/08aeda33a16a7e4106c6abbae1af7aaafce85b96)


最新のdevelopにESLintに関する変更があるので、マージしてコンフリクトの解消にチャレンジしてみてください！

2023-07-29 14:11 UTC, nyatinte requested changes
LGTM👀

[🎨AirbnbのESLintルールを適応](https://github.com/ycu-engine/DSC-Blog-Frontend/pull/10/commits/759d0d23e4830cd238e90cfd8b20365b24ce0a01)

[🎨JSDocの記述を必須とするESLintの設定を追記](https://github.com/ycu-engine/DSC-Blog-Frontend/pull/10/commits/08aeda33a16a7e4106c6abbae1af7aaafce85b96)

最新のdevelopにESLintに関する変更があるので、マージしてコンフリクトの解消にチャレンジしてみてください！

2023-07-30 01:08 UTC, takuya-okada-01 commented
@nyatinte 

先にpullしてから作業したからESlintの変更はすでに反映されてるかもなんだけど、この場合どうやって、Changes requested に対応したことになるのかな？？


↓↓画像にしたがってやってみたんだけどマージできなくて
![image](https://github.com/ycu-engine/DSC-Blog-Frontend/assets/106806920/fb1b64d3-b151-473a-8cd9-b64a4370887b)

2023-07-30 03:58 UTC, nyatinte commented
このブランチでgit fetch --allして、git merge origin/developしたらどうなる？

もし今のブランチが壊れていたら、適当なブランチにSwitchして、ブランチ消して再作成すると治るかも

2023-07-31 05:19 UTC, nyatinte approved these changes

2023-07-31 05:21 UTC, merged